<a href="https://colab.research.google.com/github/chrismanzala/rproject/blob/Python-development/TP1_Optimisation_CHRISTIAN_MANZALA_KUMBI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# $$\textbf{Régressions}$$

### $$\textit{Régression linéaire}$$ 

In [28]:
# Importation des modules et packages
import numpy as np
import pandas as pd 
import sklearn as sk
import tensorflow as tf
from tensorflow import keras

In [2]:
pros = pd.read_csv(
    "https://raw.githubusercontent.com/selva86/datasets/master/prostate.csv", 
    delimiter = ",")

In [3]:
pd.DataFrame(pros)

pros.head(3)

lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45      lpsa
0 -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0 -0.430783
1 -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0 -0.162519
2 -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20 -0.162519

In [4]:
pros_lin = np.asarray(pros)
print(pros_lin[0:3, :])

[[-0.5798185   2.769459   50.         -1.38629436  0.         -1.38629436
   6.          0.         -0.4307829 ]
 [-0.99425227  3.319626   58.         -1.38629436  0.         -1.38629436
   6.          0.         -0.1625189 ]
 [-0.51082562  2.691243   74.         -1.38629436  0.         -1.38629436
   7.         20.         -0.1625189 ]]


In [5]:
pros_lin.shape

(97, 9)

In [6]:
X_lin = pros_lin[:,0:8]
y_lin = pros_lin[:,8]


In [7]:
#importation du module de la régression linéaire
from sklearn.linear_model import LinearRegression 

model_lin = LinearRegression().fit(X_lin, y_lin) #régression linéaire

model_lin.score(X_lin, y_lin) #Coefficient d'ajustement 

0.6633895652370272

In [8]:
model_lin.intercept_ #ordonnée à l'origine

0.1815608619872373

In [9]:
model_lin.coef_ #estimations de paramètres

array([ 0.56434128,  0.62201979, -0.02124818,  0.09671252,  0.7616734 ,
       -0.10605094,  0.04922793,  0.00445751])

### $$\textit{Régression logistique}$$

In [13]:
leaf  = pd.read_csv("leafshape17.csv", delimiter = ",")

leaf

Unnamed: 0   bladelen   petiole  bladewid  latitude    logwid    logpet  \
0          186   6.930000  0.449064      3.10      17.1  1.131402 -0.800590   
1          187   7.270000  0.261720      2.50      17.1  0.916291 -1.340480   
2          188   7.430000  0.766033      2.98      17.1  1.091923 -0.266530   
3          189   8.000000  0.592800      3.06      17.1  1.118415 -0.522898   
4          190   8.080000  0.492900      3.03      17.1  1.108563 -0.707449   
..         ...        ...       ...       ...       ...       ...       ...   
56         242  25.275000  3.634545      6.85      17.1  1.924249  1.290484   
57         243  26.550000  2.635088      5.92      17.1  1.778336  0.968916   
58         244  26.992500  3.835634      8.53      17.1  2.143589  1.344335   
59         245  35.843333  3.799393      9.51      17.1  2.252344  1.334841   
60         246  42.275000  1.494421     23.45      17.1  3.154870  0.401739   

      loglen  arch  
0   1.935860     0  
1   1.983756     0  
2   2.005526     0  
3   2.079442     0  
4   2.089392     0  
..       ...   ...  
56  3.229816     1  
57  3.279030     1  
58  3.295559     1  
59  3.579158     1  
60  3.744196     1  

[61 rows x 9 columns]

In [14]:
leaf_log = np.asarray(leaf)

leaf_log[0:2,:]

array([[186.        ,   6.93      ,   0.449064  ,   3.1       ,
         17.1       ,   1.13140211,  -0.80058986,   1.93585981,
          0.        ],
       [187.        ,   7.27      ,   0.26172   ,   2.5       ,
         17.1       ,   0.91629073,  -1.34048005,   1.98375629,
          0.        ]])

In [15]:
leaf_log.shape

(61, 9)

In [16]:
X_log = np.delete(leaf_log,[0,4,8], axis = 1)

X_log[0:2,:]

array([[ 6.93      ,  0.449064  ,  3.1       ,  1.13140211, -0.80058986,
         1.93585981],
       [ 7.27      ,  0.26172   ,  2.5       ,  0.91629073, -1.34048005,
         1.98375629]])

In [17]:
y_log = leaf_log[:, 8]

In [18]:
#importation du module de la régression logistique
from sklearn.linear_model import LogisticRegression 
 
model_log = LogisticRegression().fit(X_log,y_log) #régression logistique 

model_log.score(X_log, y_log) #Coefficient d'ajustement 


0.8852459016393442

In [19]:
model_log.intercept_ #ordonnée à l'origine

array([-4.88833627])

In [20]:
model_log.coef_ #estimations de paramètres

array([[ 0.13269905,  1.29928396, -0.0677831 , -0.17083012,  0.70320759,
         0.36588237]])

# $$\textbf{Introduction à Keras}$$

In [21]:
from keras.models import Sequential
from keras.layers import Dense

In [22]:
from keras.engine import sequential
# Definition d'un réseau de neurones de type séquentiel
perceptron = Sequential()
#Défintion de sa couche cachée 
perceptron.add(Dense(units=1,  input_dim=8, activation="linear"))


In [23]:
from keras.optimizers import SGD

sgd = SGD() # descente de gradient stochastique

perceptron.compile(loss = "mean_squared_error", #critère des moindres carrés
                   optimizer = SGD(0.0001),
                    #descente de gradient avec taux d'apprentissage
                   metrics = ["accuracy"] #métrique "Précision"
                   )


In [24]:
perceptron.summary() #structure du réseau défini

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [25]:
#apprentissage du réseau
history = perceptron.fit(X_lin, y_lin, batch_size= 30, epochs = 10) 

Epoch 1/10
4/4 [==============================] - 2s 11ms/step - loss: 18.0383 - accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 9ms/step - loss: 3.5528 - accuracy: 0.0000e+00
Epoch 3/10
4/4 [==============================] - 0s 35ms/step - loss: 3.0979 - accuracy: 0.0000e+00
Epoch 4/10
4/4 [==============================] - 0s 14ms/step - loss: 3.3923 - accuracy: 0.0000e+00
Epoch 5/10
4/4 [==============================] - 0s 14ms/step - loss: 2.8120 - accuracy: 0.0000e+00
Epoch 6/10
4/4 [==============================] - 0s 11ms/step - loss: 2.8627 - accuracy: 0.0000e+00
Epoch 7/10
4/4 [==============================] - 0s 11ms/step - loss: 2.8502 - accuracy: 0.0000e+00
Epoch 8/10
4/4 [==============================] - 0s 19ms/step - loss: 2.8602 - accuracy: 0.0000e+00
Epoch 9/10
4/4 [==============================] - 0s 19ms/step - loss: 2.6960 - accuracy: 0.0000e+00
Epoch 10/10
4/4 [==============================] - 0s 13ms/step - loss: 2.9214 - accuracy: 

la précision (accuracy) à la 10ème itération reste à  0 car il n'y a pas assez de données en entrée pour favoriser l'apprentissage à partir de notre modèle.




In [27]:
perceptron.get_weights() #affichage des poids estimés(paramètres du modèle)

[array([[ 0.78079456],
        [-0.1334844 ],
        [ 0.09019651],
        [ 0.60828984],
        [-0.6444202 ],
        [ 0.78979385],
        [-0.6735001 ],
        [-0.0160362 ]], dtype=float32),
 array([-0.00107876], dtype=float32)]